testcurrency/testcurrency/urls.py
from django.conf.urls import url
from django.contrib import admin
from currency import views as currency_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', currency_views.IndexView.as_view(), name='index'),
    url(r'^currencies/$', currency_views.CurrencyListView.as_view(), name='currencies'),
    url(r'^currency/(?P<pk>\d+)$', currency_views.CurrencyDetailView.as_view(), name='currency-detail'),
    url(r'^ajax-example/$', currency_views.AjaxExample.as_view(), name='ajax-example'),
    url(r'^converter/$', currency_views.Converter.as_view(), name='converter'),
]

testcurrency/currency/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from decimal import Decimal as D

from django.db import models


class Currency(models.Model):
    code = models.CharField(max_length=3)
    name = models.CharField(max_length=100)
    show_rate = models.BooleanField(default=False)

    def __unicode__(self):
        return u'{}'.format(self.code)

    def as_json(self):
        rate = None
        if self.rate_set.first():
            rate = str(self.rate_set.first().rate)
        return {
            "id": self.id,
            "code": self.code,
            "name": self.name,
            "rate": rate
        }


class Rate(models.Model):
    currency = models.ForeignKey(Currency)
    rate = models.DecimalField(decimal_places=6, max_digits=16, default=D('0.000000'))
    date_updated = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return u'{} {}'.format(self.currency.code, self.rate)

    def as_json(self):
        return {
            "id": self.id,
            "currency": self.currency.code,
            "currency_name": self.currency.name,
            "rate": self.rate,
            "date_updated": self.date_updated
        }

testcurrency/currency/forms.py
# -*- coding: utf-8 -*-

from decimal import Decimal
from django import forms
from .models import Currency


class CurrencyForm(forms.Form):
    currency = forms.ModelChoiceField(queryset=Currency.objects.filter(show_rate=True))


class ConverterForm(forms.Form):
    amount_money =forms.DecimalField(max_digits=16, decimal_places=2, initial=Decimal('5.00'), required=True)
    currency1 = forms.ModelChoiceField(label='From', queryset=Currency.objects.filter(show_rate=True), initial=Currency.objects.first())
    currency2 = forms.ModelChoiceField(label='To',queryset=Currency.objects.filter(show_rate=True), initial=Currency.objects.first())

testcurrency/currency/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import json
from decimal import Decimal
from django.http import JsonResponse
from django.shortcuts import render
from django.views import generic
from django.http import HttpResponse

from . import models
from .forms import CurrencyForm, ConverterForm


class IndexView(generic.TemplateView):
    template_name = "index.html"


class JSONResponseMixin(object):
    def render_to_json_response(self, context, **response_kwargs):
        if 'object' in context:
            data = self.object.as_json()
            dump = json.dumps(data)
        if 'object_list' in context:
            data = [ obj.as_json() for obj in self.object_list]
            dump = json.dumps(data)
        return HttpResponse(dump, content_type='application/json')



class CurrencyListView(JSONResponseMixin, generic.ListView):
    model = models.Currency
    queryset = models.Currency.objects.filter(show_rate=True)
    template_name = 'currency/currency_list.html'

    def render_to_response(self, context):
        if self.request.GET.get('format') == 'json' or self.request.is_ajax():
            return self.render_to_json_response(context)
        else:
            context['json'] = self.render_to_json_response(context)
            return super(CurrencyListView, self).render_to_response(context)


class CurrencyDetailView(JSONResponseMixin, generic.DetailView):
    model = models.Currency
    template_name = 'currency/currency_detail.html'

    def render_to_response(self, context):
        # Look for a 'format=json' GET argument
        if self.request.GET.get('format') == 'json' or self.request.is_ajax():
            return self.render_to_json_response(context)
        else:
            return super(CurrencyDetailView, self).render_to_response(context)


class AjaxExample(generic.TemplateView):
    template_name = "currency/ajax_example.html"
    form = CurrencyForm()

    def render_to_response(self, context):
        context['form'] = self.form
        return super(AjaxExample, self).render_to_response(context)


class AjaxableResponseMixin:
    def form_invalid(self, form):
        response = super().form_invalid(form)
        if self.request.is_ajax():
            return JsonResponse(form.errors, status=400)
        else:
            return response

    def form_valid(self, form):
        response = super().form_valid(form)
        if self.request.is_ajax():
            data = {
                'pk': self.object.pk,
            }
            return JsonResponse(data)
        else:
            return response


class Converter(generic.TemplateView):
    template_name = "currency/converter.html"
    form = ConverterForm()

    def render_to_response(self, context):
        context['form'] = self.form
        return super(Converter, self).render_to_response(context)

    def post(self,request):
        if request.is_ajax():
            form=ConverterForm(request.POST)
            response_data = {}
            if form.is_valid():
                amount_money = request.POST['amount_money']
                currency1 = request.POST['currency1']
                currency2 = request.POST['currency2']
                rate1=models.Rate.objects.get(currency_id=currency1)
                rate2=models.Rate.objects.get(currency_id=currency2)
                print(rate2)
                response_data['result'] = (Decimal(amount_money)/rate1.rate*rate2.rate).quantize(Decimal('0.01'))
            else:
                response_data['result'] = form.errors
            return JsonResponse(response_data)

testcurrency/currency/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}

<head>
	<title>{% block title %}Currencies{% endblock %}</title>

  {% block extrastyles %}{% endblock %}
</head>

<body>
	<div class="">
		{% block menu %}
			<a href="{% url 'currencies' %}">Currency list</a>
			<a href="{% url 'ajax-example' %}">Ajax Currency Rate</a>
			<a href="{% url 'converter' %}">Ajax Converter</a>
		{% endblock %}
	</div>
	<div class="">
		{% block content %}
		{% endblock %}
	</div>

	{% block extrascripts %}
	{% endblock %}

</body>
</html>

testcurrency/currency/templates/currency/ajax_example.html
{% extends "base.html" %}

{% block content %}
  <br>
  <p>Get rate for</p>
  <form id="currencyForm" class="" action="" method="post">
    {% csrf_token %}
    {{form}}
    <input type="submit" name="" value="Get rate">
  </form>
  <br>
  <div id="ajax-response" class="">
  </div>

{% endblock %}


{% block extrascripts %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

  <script>

    (function(){
      var currencyForm = $('#currencyForm');

      currencyForm.on('submit', function(){
        console.log('submit', currencyForm.serializeArray());
        $.ajax({
            // type: currencyForm.attr('method'),
            type: 'get',
            url: '/currency/'+currencyForm.serializeArray()[1].value,
            data: currencyForm.serialize(),
            success: function (response_data) {
              console.log('success ajax: ', response_data);
              $('#ajax-response').text('1 USD = '+response_data.rate);
            },
            error: function(data) {
              console.log('error ajax: ', data);
              alert('Error post data');
            }
        });
        return false;
      });
    })()

  </script>
{% endblock %}

testcurrency/currency/templates/currency/converter.html
{% extends "base.html" %}

{% block content %}

  <h1>Converter</h1>
  <form id="currencyForm" class="" action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" name="" value="Convert">
  </form>
  <br>
  <div id="ajax-response" class="">
  </div>

{% endblock %}


{% block extrascripts %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

  <script>

    (function(){
      $("#id_amount_money").attr('max','999999999999');

      var currencyForm = $('#currencyForm');

      currencyForm.on('submit', function(){
        console.log('submit', currencyForm.serializeArray());
        $.ajax({
            // type: currencyForm.attr('method'),
            type: 'post',
            url: '.',
            data: currencyForm.serialize(),
            success: function (response_data) {
              console.log('success ajax: ', response_data);
              $('#ajax-response').text(response_data.result);
            },
            error: function(data) {
              console.log('error ajax: ', data);
              alert('Error post data');
            }
        });
        return false;
      });
    })()

  </script>
{% endblock %}

testcurrency/currency/templates/currency/currency_detail.html
{% extends "base.html" %}

{% block content %}
    <h1>Currency: {{currency.code}}</h1>

    <p>{{currency.name}}</p>
    <p>{{currency.code}}</p>
    {% with rate=currency.rate_set.first %}
      {{rate.rate}}
    {% endwith %}
{% endblock %}

testcurrency/currency/templates/currency/currency_list.html
{% extends "base.html" %}

{% block content %}
    <h1>Currency List</h1>

    {% if currency_list %}
    <ul>

      {% for currency in currency_list %}
      <li>
        <a href="{% url 'currency-detail' currency.pk %}">{{ currency.name }}</a> ({{currency.code}})
      </li>
      {% endfor %}

    </ul>
    <h2>Json response</h2>
    <p>{{json}}</p>

    {% else %}
      <p>There are no currencies.</p>
    {% endif %}
{% endblock %}

testcurrency/currency/templates/index.html
{% extends "base.html" %}